name: Keep Active
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config --global user.name "MarchAlva"
          git config --global user.email "702636447@qq.com"
          git commit --allow-empty -m "Automated commit to keep repo active"
          git push
